import Config

# Register custom metadata keys for structured logging (NeonFS.Core.Log).
# In production, runtime.exs overrides the handler with LoggerJSON.Formatters.Basic.
# The :default_formatter config is also read by Credo's MissedMetadataKeyInLoggerConfig check.
config :logger, :default_formatter,
  metadata: [
    :action,
    :app,
    :apps,
    :atime_mode,
    :attempt,
    :available,
    :backoff_ms,
    :bootstrap_expect,
    :bytes_moved,
    :change,
    :check_interval_ms,
    :chunk_hash,
    :chunks_migrated,
    :cleaned,
    :cluster_id,
    :cluster_name,
    :command_type,
    :component,
    :config,
    :configured_capacity,
    :connected,
    :core_count,
    :core_node,
    :count,
    :current_size,
    :days_remaining,
    :decayed,
    :dets_path,
    :drive_count,
    :drive_id,
    :drive_type,
    :dry_run,
    :enable_ra,
    :error,
    :errors,
    :ets_table,
    :event_type,
    :existing_members,
    :expected,
    :expected_hash,
    :failure_count,
    :file_path,
    :from,
    :init_node,
    :interval_ms,
    :job_id,
    :job_label,
    :joining_node,
    :kind,
    :label,
    :leader,
    :max_attempts,
    :max_concurrent,
    :max_memory_bytes,
    :members,
    :message,
    :meta_dir,
    :mount_id,
    :mount_point,
    :new_expiry,
    :node,
    :node_count,
    :node_name,
    :node_named,
    :num_acceptors,
    :old_expiry,
    :operation,
    :partition_total,
    :path,
    :peer,
    :peer_count,
    :peers,
    :phase,
    :pid,
    :port,
    :pressure_check_interval_ms,
    :pressure_threshold,
    :previous_size,
    :queued,
    :ra_config,
    :ratio,
    :ready,
    :reason,
    :remaining,
    :request_id,
    :requested,
    :required,
    :result,
    :retry_minutes,
    :root_inode,
    :running_count,
    :scheduler,
    :segment_count,
    :server_id,
    :skew_ms,
    :succeeded,
    :table_name,
    :temp_path,
    :threshold,
    :tier,
    :tiers,
    :to,
    :type,
    :volume,
    :volume_id,
    :volume_name,
    :work_id,
    :work_label
  ]

config :logger, :default_handler,
  formatter:
    {Logger.Formatter,
     metadata: [
       :action,
       :app,
       :apps,
       :atime_mode,
       :attempt,
       :available,
       :backoff_ms,
       :bootstrap_expect,
       :bytes_moved,
       :change,
       :check_interval_ms,
       :chunk_hash,
       :chunks_migrated,
       :cleaned,
       :cluster_id,
       :cluster_name,
       :command_type,
       :component,
       :config,
       :configured_capacity,
       :connected,
       :core_count,
       :core_node,
       :count,
       :current_size,
       :days_remaining,
       :decayed,
       :dets_path,
       :drive_count,
       :drive_id,
       :drive_type,
       :dry_run,
       :enable_ra,
       :error,
       :errors,
       :ets_table,
       :event_type,
       :existing_members,
       :expected,
       :expected_hash,
       :failure_count,
       :file_path,
       :from,
       :init_node,
       :interval_ms,
       :job_id,
       :job_label,
       :joining_node,
       :kind,
       :label,
       :leader,
       :max_attempts,
       :max_concurrent,
       :max_memory_bytes,
       :members,
       :message,
       :meta_dir,
       :mount_id,
       :mount_point,
       :new_expiry,
       :node,
       :node_count,
       :node_name,
       :node_named,
       :num_acceptors,
       :old_expiry,
       :operation,
       :partition_total,
       :path,
       :peer,
       :peer_count,
       :peers,
       :phase,
       :pid,
       :port,
       :pressure_check_interval_ms,
       :pressure_threshold,
       :previous_size,
       :queued,
       :ra_config,
       :ratio,
       :ready,
       :reason,
       :remaining,
       :request_id,
       :requested,
       :required,
       :result,
       :retry_minutes,
       :root_inode,
       :running_count,
       :scheduler,
       :segment_count,
       :server_id,
       :skew_ms,
       :succeeded,
       :table_name,
       :temp_path,
       :threshold,
       :tier,
       :tiers,
       :to,
       :type,
       :volume,
       :volume_id,
       :volume_name,
       :work_id,
       :work_label
     ]}

config :neonfs_core,
  # Toggle observability stack (Prometheus reporter + poller + HTTP endpoint)
  metrics_enabled: true,
  # Bind address for /metrics and /health
  metrics_bind: "0.0.0.0",
  # Port for /metrics and /health
  metrics_port: 9568

# Example cluster.json section for overriding metrics settings:
# "metrics": {
#   "enabled": false,
#   "bind": "127.0.0.1",
#   "port": 9568,
#   "poll_interval_ms": 15000
# }

# Test environment configuration
if Mix.env() == :test do
  # Suppress log output during tests (ExUnit's capture_log handles test-specific logs)
  config :logger, level: :warning

  # Ra's own data_dir config — without this, :ra_system.start_default()
  # writes into the current working directory (creating node-named dirs in the project root)
  config :ra,
    data_dir: ~c"/tmp/neonfs_test/ra"

  config :neonfs_core,
    blob_store_base_dir: "/tmp/neonfs_test/blobs",
    drives: [%{id: "default", path: "/tmp/neonfs_test/blobs", tier: :hot, capacity: 0}],
    meta_dir: "/tmp/neonfs_test/meta",
    metrics_enabled: false,
    ra_data_dir: "/tmp/neonfs_test/ra",
    snapshot_interval_ms: 100,
    enable_ra: true,
    # Don't auto-start children in tests - each test starts what it needs
    start_children?: false
end

if Mix.env() in [:dev, :test] do
  config :git_ops,
    mix_project: Mix.Project.get!(),
    types: [tidbit: [hidden?: true], important: [header: "Important Changes"]],
    github_handle_lookup?: false,
    version_tag_prefix: "v",
    manage_mix_version?: true,
    manage_readme_version: true
end
