defmodule NeonFS.Core.Blob.Native do
  @moduledoc """
  Native Rust NIF bindings for blob storage operations.

  This module provides low-level bindings to the neonfs_blob Rust crate,
  which handles content-addressed chunk storage, chunking algorithms,
  compression, and encryption.
  """

  use Rustler,
    otp_app: :neonfs_core,
    crate: :neonfs_blob

  @type store :: reference()
  @type hash :: binary()
  @type tier :: String.t()

  @doc """
  Test function that adds two integers.

  This is the default NIF function generated by Rustler for verification.
  It will be replaced with actual blob storage functions in subsequent tasks.
  """
  @spec add(integer(), integer()) :: integer()
  def add(_a, _b), do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Computes the SHA-256 hash of the given binary data.

  The hash is computed on the raw data as provided - no compression or
  encryption is applied. This ensures consistent content addressing
  regardless of storage format.

  ## Parameters
    - `data` - Binary data to hash

  ## Returns
    - A 32-byte binary containing the SHA-256 hash

  ## Examples

      iex> hash = NeonFS.Core.Blob.Native.compute_hash("hello world")
      iex> byte_size(hash)
      32

  """
  @spec compute_hash(binary()) :: binary()
  def compute_hash(_data), do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Opens a blob store at the given base directory.

  The store manages content-addressed chunk storage on disk using a sharded
  directory hierarchy based on hash prefixes.

  ## Parameters
    - `base_dir` - Path to the base directory for blob storage
    - `prefix_depth` - Number of prefix directory levels (e.g., 2 for 65K directories)

  ## Returns
    - `{:ok, store}` - A reference to the opened store
    - `{:error, reason}` - If the store could not be opened

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> is_reference(store)
      true

  """
  @spec store_open(String.t(), non_neg_integer()) :: {:ok, store()} | {:error, String.t()}
  def store_open(_base_dir, _prefix_depth), do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Writes a chunk to the blob store.

  The chunk is written atomically using a write-then-rename pattern to prevent
  partial chunks on disk. If a chunk with the same hash already exists, this
  operation is idempotent.

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - 32-byte binary hash of the chunk data
    - `data` - Binary data to write
    - `tier` - Storage tier ("hot", "warm", or "cold")

  ## Returns
    - `{:ok, {}}` - On success
    - `{:error, reason}` - If the write fails

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> data = "hello world"
      iex> hash = NeonFS.Core.Blob.Native.compute_hash(data)
      iex> {:ok, _} = NeonFS.Core.Blob.Native.store_write_chunk(store, hash, data, "hot")

  """
  @spec store_write_chunk(store(), hash(), binary(), tier()) :: {:ok, {}} | {:error, String.t()}
  def store_write_chunk(_store, _hash, _data, _tier), do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Reads a chunk from the blob store.

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - 32-byte binary hash of the chunk
    - `tier` - Storage tier ("hot", "warm", or "cold")

  ## Returns
    - `{:ok, data}` - The chunk data as a binary
    - `{:error, reason}` - If the chunk does not exist or read fails

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> data = "hello world"
      iex> hash = NeonFS.Core.Blob.Native.compute_hash(data)
      iex> {:ok, _} = NeonFS.Core.Blob.Native.store_write_chunk(store, hash, data, "hot")
      iex> {:ok, read_data} = NeonFS.Core.Blob.Native.store_read_chunk(store, hash, "hot")
      iex> read_data == data
      true

  """
  @spec store_read_chunk(store(), hash(), tier()) :: {:ok, binary()} | {:error, String.t()}
  def store_read_chunk(_store, _hash, _tier), do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Reads a chunk from the blob store with optional verification.

  When `verify` is true, the function computes the SHA-256 hash of the data
  after reading and compares it to the expected hash. If they don't match,
  an error is returned indicating the chunk is corrupt.

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - 32-byte binary hash of the chunk
    - `tier` - Storage tier ("hot", "warm", or "cold")
    - `verify` - If true, verify the data matches the expected hash

  ## Returns
    - `{:ok, data}` - The chunk data as a binary
    - `{:error, reason}` - If the chunk does not exist, read fails, or verification fails

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> data = "hello world"
      iex> hash = NeonFS.Core.Blob.Native.compute_hash(data)
      iex> {:ok, _} = NeonFS.Core.Blob.Native.store_write_chunk(store, hash, data, "hot")
      iex> {:ok, read_data} = NeonFS.Core.Blob.Native.store_read_chunk_verified(store, hash, "hot", true)
      iex> read_data == data
      true

  """
  @spec store_read_chunk_verified(store(), hash(), tier(), boolean()) ::
          {:ok, binary()} | {:error, String.t()}
  def store_read_chunk_verified(_store, _hash, _tier, _verify),
    do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Deletes a chunk from the blob store.

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - 32-byte binary hash of the chunk
    - `tier` - Storage tier ("hot", "warm", or "cold")

  ## Returns
    - `{:ok, {}}` - On success
    - `{:error, reason}` - If the chunk does not exist or delete fails

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> data = "hello world"
      iex> hash = NeonFS.Core.Blob.Native.compute_hash(data)
      iex> {:ok, _} = NeonFS.Core.Blob.Native.store_write_chunk(store, hash, data, "hot")
      iex> {:ok, _bytes_freed} = NeonFS.Core.Blob.Native.store_delete_chunk(store, hash, "hot")

  """
  @spec store_delete_chunk(store(), hash(), tier()) ::
          {:ok, non_neg_integer()} | {:error, String.t()}
  def store_delete_chunk(_store, _hash, _tier), do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Checks if a chunk exists in the blob store.

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - 32-byte binary hash of the chunk
    - `tier` - Storage tier ("hot", "warm", or "cold")

  ## Returns
    - `{:ok, true}` - If the chunk exists
    - `{:ok, false}` - If the chunk does not exist
    - `{:error, reason}` - If the check fails

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> hash = NeonFS.Core.Blob.Native.compute_hash("test")
      iex> {:ok, false} = NeonFS.Core.Blob.Native.store_chunk_exists(store, hash, "hot")

  """
  @spec store_chunk_exists(store(), hash(), tier()) :: {:ok, boolean()} | {:error, String.t()}
  def store_chunk_exists(_store, _hash, _tier), do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Migrates a chunk from one storage tier to another.

  This operation is atomic: the chunk is copied to the destination tier,
  verified for integrity, and only then deleted from the source tier.
  If any step fails, the migration is aborted and the source chunk remains intact.

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - SHA-256 hash of the chunk (32 bytes)
    - `from_tier` - Source tier: "hot", "warm", or "cold"
    - `to_tier` - Destination tier: "hot", "warm", or "cold"

  ## Returns
    - `{:ok, {}}` on successful migration
    - `{:error, reason}` if the chunk doesn't exist or migration fails

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/store", 2)
      iex> data = "migrate me"
      iex> hash = NeonFS.Core.Blob.Native.compute_hash(data)
      iex> {:ok, _} = NeonFS.Core.Blob.Native.store_write_chunk(store, hash, data, "hot")
      iex> {:ok, _} = NeonFS.Core.Blob.Native.store_migrate_chunk(store, hash, "hot", "cold")
      iex> {:ok, false} = NeonFS.Core.Blob.Native.store_chunk_exists(store, hash, "hot")
      iex> {:ok, true} = NeonFS.Core.Blob.Native.store_chunk_exists(store, hash, "cold")

  """
  @spec store_migrate_chunk(store(), hash(), tier(), tier()) ::
          {:ok, {}} | {:error, String.t()}
  def store_migrate_chunk(_store, _hash, _from_tier, _to_tier),
    do: :erlang.nif_error(:nif_not_loaded)

  @type compression :: String.t()
  @type chunk_info :: {non_neg_integer(), non_neg_integer(), compression()}

  @doc """
  Writes a chunk to the blob store with optional compression and encryption.

  The hash is computed on the original (uncompressed, unencrypted) data.
  Pipeline order: compress → encrypt → write to disk.

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - 32-byte binary hash of the original (uncompressed) chunk data
    - `data` - Binary data to write
    - `tier` - Storage tier ("hot", "warm", or "cold")
    - `compression` - Compression type: "none" or "zstd"
    - `compression_level` - Compression level (1-19, used for zstd only)
    - `key` - 32-byte AES-256 key for encryption, or `<<>>` for no encryption
    - `nonce` - 12-byte nonce for encryption, or `<<>>` for no encryption

  ## Returns
    - `{:ok, {original_size, stored_size, compression, encryption_algorithm, nonce}}` - On success
    - `{:error, reason}` - If the write fails

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> data = String.duplicate("hello world", 1000)
      iex> hash = NeonFS.Core.Blob.Native.compute_hash(data)
      iex> {:ok, {orig, stored, comp, _enc, _nonce}} = NeonFS.Core.Blob.Native.store_write_chunk_compressed(
      ...>   store, hash, data, "hot", "zstd", 3, <<>>, <<>>
      ...> )
      iex> stored < orig
      true
      iex> comp
      "zstd:3"

  """
  @type encryption_info ::
          {non_neg_integer(), non_neg_integer(), compression(), String.t(), binary()}

  @spec store_write_chunk_compressed(
          store(),
          hash(),
          binary(),
          tier(),
          compression(),
          integer(),
          binary(),
          binary()
        ) :: {:ok, encryption_info()} | {:error, String.t()}
  def store_write_chunk_compressed(
        _store,
        _hash,
        _data,
        _tier,
        _compression,
        _compression_level,
        _key,
        _nonce
      ),
      do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Reads a chunk from the blob store with optional verification, decompression,
  and decryption.

  This is the most flexible read function, supporting integrity verification,
  transparent decompression, and decryption.
  Pipeline order: read → decrypt → decompress → verify.

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - 32-byte binary hash of the original (uncompressed) chunk data
    - `tier` - Storage tier ("hot", "warm", or "cold")
    - `verify` - If true, verify the data matches the expected hash after decompression
    - `decompress` - If true, decompress the data after reading
    - `key` - 32-byte AES-256 key for decryption, or `<<>>` for no decryption
    - `nonce` - 12-byte nonce for decryption, or `<<>>` for no decryption

  ## Returns
    - `{:ok, data}` - The chunk data as a binary (decrypted and/or decompressed if requested)
    - `{:error, reason}` - If the chunk does not exist, read fails, decryption
      fails, decompression fails, or verification fails

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> data = String.duplicate("hello world", 1000)
      iex> hash = NeonFS.Core.Blob.Native.compute_hash(data)
      iex> {:ok, _} = NeonFS.Core.Blob.Native.store_write_chunk_compressed(
      ...>   store, hash, data, "hot", "zstd", 3, <<>>, <<>>
      ...> )
      iex> {:ok, read_data} = NeonFS.Core.Blob.Native.store_read_chunk_with_options(
      ...>   store, hash, "hot", true, true, <<>>, <<>>
      ...> )
      iex> read_data == data
      true

  """
  @spec store_read_chunk_with_options(
          store(),
          hash(),
          tier(),
          boolean(),
          boolean(),
          binary(),
          binary()
        ) ::
          {:ok, binary()} | {:error, String.t()}
  def store_read_chunk_with_options(_store, _hash, _tier, _verify, _decompress, _key, _nonce),
    do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Re-encrypts a chunk in place: decrypts with old key/nonce, re-encrypts with
  new key/nonce, writes back atomically.

  The entire decrypt → re-encrypt cycle happens in Rust without any data
  crossing the NIF boundary. Compression is preserved (only the encryption
  layer changes).

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - 32-byte binary hash of the chunk
    - `tier` - Storage tier ("hot", "warm", or "cold")
    - `old_key` - 32-byte AES-256 key used for current encryption
    - `old_nonce` - 12-byte nonce used for current encryption
    - `new_key` - 32-byte AES-256 key for new encryption
    - `new_nonce` - 12-byte nonce for new encryption

  ## Returns
    - `{:ok, stored_size}` - The stored size of the re-encrypted chunk
    - `{:error, reason}` - If the chunk does not exist or re-encryption fails
  """
  @spec store_reencrypt_chunk(
          store(),
          hash(),
          tier(),
          binary(),
          binary(),
          binary(),
          binary()
        ) :: {:ok, non_neg_integer()} | {:error, String.t()}
  def store_reencrypt_chunk(_store, _hash, _tier, _old_key, _old_nonce, _new_key, _new_nonce),
    do: :erlang.nif_error(:nif_not_loaded)

  # Chunking types
  @type chunk_result :: {binary(), hash(), non_neg_integer(), non_neg_integer()}
  @type chunk_strategy :: String.t()

  @doc """
  Splits data into chunks using the specified strategy.

  The chunking strategy determines how data is divided:
  - "single": Store as a single chunk (good for small files)
  - "fixed": Split into fixed-size chunks (good for medium files)
  - "fastcdc": Use content-defined chunking (good for deduplication)
  - "auto": Automatically select based on data length

  ## Parameters
    - `data` - Binary data to split into chunks
    - `strategy` - Chunking strategy: "single", "fixed", "fastcdc", or "auto"
    - `strategy_param` - Strategy-specific parameter:
      - For "single": ignored (pass 0)
      - For "fixed": chunk size in bytes (required, must be > 0)
      - For "fastcdc": average chunk size in bytes (0 for default 256KB)
      - For "auto": data length (used to select appropriate strategy)

  ## Returns
    - `{:ok, chunks}` - A list of tuples, each containing:
      - `data` - The chunk data as a binary
      - `hash` - SHA-256 hash of the chunk (32 bytes)
      - `offset` - Byte offset of this chunk in the original data
      - `size` - Size of this chunk in bytes
    - `{:error, reason}` - If the strategy is invalid

  ## Examples

      iex> data = String.duplicate("hello world ", 100)
      iex> {:ok, chunks} = NeonFS.Core.Blob.Native.chunk_data(data, "single", 0)
      iex> length(chunks)
      1
      iex> {chunk_data, _hash, offset, size} = hd(chunks)
      iex> chunk_data == data
      true
      iex> offset
      0
      iex> size == byte_size(data)
      true

  """
  @spec chunk_data(binary(), chunk_strategy(), non_neg_integer()) ::
          {:ok, [chunk_result()]} | {:error, String.t()}
  def chunk_data(data, strategy, strategy_param) do
    nif_chunk_data(data, strategy, strategy_param)
  end

  @doc false
  @spec nif_chunk_data(binary(), chunk_strategy(), non_neg_integer()) ::
          {:ok, [chunk_result()]} | {:error, String.t()}
  def nif_chunk_data(_data, _strategy, _strategy_param),
    do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Determines the appropriate chunking strategy for the given data length.

  This function implements the automatic strategy selection:
  - < 64KB: "single" strategy (avoid chunking overhead)
  - 64KB - 1MB: "fixed" strategy with 256KB chunks
  - >= 1MB: "fastcdc" strategy for content-defined chunking

  ## Parameters
    - `data_len` - Length of the data in bytes

  ## Returns
    - `{strategy, param}` - A tuple of the recommended strategy name and parameter

  ## Examples

      iex> NeonFS.Core.Blob.Native.auto_chunk_strategy(1000)
      {"single", 0}

      iex> NeonFS.Core.Blob.Native.auto_chunk_strategy(100_000)
      {"fixed", 262144}

      iex> NeonFS.Core.Blob.Native.auto_chunk_strategy(2_000_000)
      {"fastcdc", 262144}

  """
  @spec auto_chunk_strategy(non_neg_integer()) :: {String.t(), non_neg_integer()}
  def auto_chunk_strategy(data_len) do
    nif_auto_chunk_strategy(data_len)
  end

  @doc false
  @spec nif_auto_chunk_strategy(non_neg_integer()) :: {String.t(), non_neg_integer()}
  def nif_auto_chunk_strategy(_data_len),
    do: :erlang.nif_error(:nif_not_loaded)

  @typedoc """
  Opaque handle to an incremental chunker resource.
  """
  @type chunker :: reference()

  @doc """
  Creates an incremental chunker that emits chunks as data is fed in.

  Use this when the total input size is unknown or larger than memory.
  Feed slices via `chunker_feed/2` and call `chunker_finish/1` once all
  input has been provided to flush any remaining buffered data.

  The strategy/`strategy_param` arguments follow the same convention as
  `chunk_data/3`.

  ## Examples

      iex> {:ok, c} = NeonFS.Core.Blob.Native.chunker_init("fixed", 4)
      iex> emitted = NeonFS.Core.Blob.Native.chunker_feed(c, "abcdefg")
      iex> length(emitted)
      1
      iex> {chunk, _hash, 0, 4} = hd(emitted)
      iex> chunk
      "abcd"
      iex> [{tail, _hash, 4, 3}] = NeonFS.Core.Blob.Native.chunker_finish(c)
      iex> tail
      "efg"

  """
  @spec chunker_init(chunk_strategy(), non_neg_integer()) ::
          {:ok, chunker()} | {:error, String.t()}
  def chunker_init(_strategy, _strategy_param),
    do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Feeds a slice of data into the chunker.

  Returns any chunks that became complete as a result of this slice. Bytes
  that may still belong to a future chunk remain buffered inside the
  resource — the working set is bounded by the strategy's maximum chunk
  size, regardless of how much data is fed in total.
  """
  @spec chunker_feed(chunker(), binary()) :: [chunk_result()]
  def chunker_feed(_chunker, _data),
    do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Flushes any remaining buffered data as the final chunks.

  After `chunker_finish/1`, the chunker may be reused with further
  `chunker_feed/2` calls; offsets continue from where they left off.
  """
  @spec chunker_finish(chunker()) :: [chunk_result()]
  def chunker_finish(_chunker),
    do: :erlang.nif_error(:nif_not_loaded)

  # Erasure coding types
  @type shard :: binary()
  @type shard_with_index :: {non_neg_integer(), binary()}

  @doc """
  Encodes data shards using Reed-Solomon erasure coding and returns parity shards.

  All data shards must be the same size. The returned parity shards will also
  be the same size as the data shards.

  ## Parameters
    - `data_shards` - List of equal-sized binary data shards
    - `parity_count` - Number of parity shards to generate

  ## Returns
    - `{:ok, parity_shards}` - List of parity shard binaries
    - `{:error, reason}` - If encoding fails

  ## Examples

      iex> data = [<<1, 2, 3, 4>>, <<5, 6, 7, 8>>, <<9, 10, 11, 12>>]
      iex> {:ok, parity} = NeonFS.Core.Blob.Native.erasure_encode(data, 2)
      iex> length(parity)
      2
      iex> byte_size(hd(parity))
      4

  """
  @spec erasure_encode([shard()], non_neg_integer()) ::
          {:ok, [shard()]} | {:error, String.t()}
  def erasure_encode(_data_shards, _parity_count),
    do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Decodes (reconstructs) missing data shards from available shards using
  Reed-Solomon erasure coding.

  Takes a list of `{index, binary}` tuples representing available shards.
  Indices 0..data_count-1 are data shards, data_count..total-1 are parity shards.
  At least `data_count` shards must be provided for reconstruction.

  ## Parameters
    - `shards_with_indices` - List of `{index, binary}` tuples for available shards
    - `data_count` - Number of data shards in the original encoding
    - `parity_count` - Number of parity shards in the original encoding
    - `shard_size` - Expected size of each shard in bytes

  ## Returns
    - `{:ok, data_shards}` - List of all reconstructed data shard binaries
    - `{:error, reason}` - If decoding fails

  ## Examples

      iex> data = [<<1, 2, 3, 4>>, <<5, 6, 7, 8>>, <<9, 10, 11, 12>>]
      iex> {:ok, parity} = NeonFS.Core.Blob.Native.erasure_encode(data, 2)
      iex> available = [{0, <<1, 2, 3, 4>>}, {2, <<9, 10, 11, 12>>}, {3, hd(parity)}]
      iex> {:ok, recovered} = NeonFS.Core.Blob.Native.erasure_decode(available, 3, 2, 4)
      iex> recovered == data
      true

  """
  @spec erasure_decode(
          [shard_with_index()],
          non_neg_integer(),
          non_neg_integer(),
          non_neg_integer()
        ) ::
          {:ok, [shard()]} | {:error, String.t()}
  def erasure_decode(_shards_with_indices, _data_count, _parity_count, _shard_size),
    do: :erlang.nif_error(:nif_not_loaded)

  # Filesystem info

  @doc """
  Returns filesystem capacity information for the given path.

  Uses `statvfs()` to query the filesystem containing `path`.

  ## Parameters
    - `path` - Absolute path to query (can be any file or directory on the filesystem)

  ## Returns
    - `{:ok, {total_bytes, available_bytes, used_bytes}}` - Filesystem capacity info
    - `{:error, reason}` - If the path doesn't exist or statvfs fails
  """
  @spec filesystem_info(String.t()) ::
          {:ok, {non_neg_integer(), non_neg_integer(), non_neg_integer()}} | {:error, String.t()}
  def filesystem_info(_path), do: :erlang.nif_error(:nif_not_loaded)

  # Metadata namespace operations

  @doc """
  Writes metadata to the blob store's metadata namespace.

  Metadata is stored under `meta/{segment_id_hex}/{prefix}/{key_hash_hex}`,
  using the same atomic write-then-rename pattern as chunk writes.

  ## Parameters
    - `store` - Reference to the blob store
    - `segment_id_hex` - Hex string identifying the metadata segment
    - `key_hash` - 32-byte binary hash of the metadata key
    - `data` - Binary metadata to write

  ## Returns
    - `{:ok, {}}` - On success
    - `{:error, reason}` - If the write fails
  """
  @spec metadata_write(store(), String.t(), hash(), binary()) :: {:ok, {}} | {:error, String.t()}
  def metadata_write(_store, _segment_id_hex, _key_hash, _data),
    do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Reads metadata from the blob store's metadata namespace.

  ## Parameters
    - `store` - Reference to the blob store
    - `segment_id_hex` - Hex string identifying the metadata segment
    - `key_hash` - 32-byte binary hash of the metadata key

  ## Returns
    - `{:ok, data}` - The metadata as a binary
    - `{:error, reason}` - If the key does not exist or read fails
  """
  @spec metadata_read(store(), String.t(), hash()) :: {:ok, binary()} | {:error, String.t()}
  def metadata_read(_store, _segment_id_hex, _key_hash),
    do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Deletes metadata from the blob store's metadata namespace.

  ## Parameters
    - `store` - Reference to the blob store
    - `segment_id_hex` - Hex string identifying the metadata segment
    - `key_hash` - 32-byte binary hash of the metadata key

  ## Returns
    - `{:ok, {}}` - On success
    - `{:error, reason}` - If the key does not exist or delete fails
  """
  @spec metadata_delete(store(), String.t(), hash()) :: {:ok, {}} | {:error, String.t()}
  def metadata_delete(_store, _segment_id_hex, _key_hash),
    do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Lists all metadata key hashes in a segment.

  Recursively walks the segment directory and returns all key hashes found.
  Temporary files are skipped. Returns an empty list for nonexistent segments.

  ## Parameters
    - `store` - Reference to the blob store
    - `segment_id_hex` - Hex string identifying the metadata segment

  ## Returns
    - `{:ok, hashes}` - List of 32-byte binary key hashes
    - `{:error, reason}` - If the listing fails
  """
  @spec metadata_list_segment(store(), String.t()) :: {:ok, [hash()]} | {:error, String.t()}
  def metadata_list_segment(_store, _segment_id_hex),
    do: :erlang.nif_error(:nif_not_loaded)
end
