defmodule NeonFS.Core.Blob.Native do
  @moduledoc """
  Native Rust NIF bindings for blob storage operations.

  This module provides low-level bindings to the neonfs_blob Rust crate,
  which handles content-addressed chunk storage, chunking algorithms,
  compression, and encryption.
  """

  use Rustler,
    otp_app: :neonfs_core,
    crate: :neonfs_blob

  @type store :: reference()
  @type hash :: binary()
  @type tier :: String.t()

  @doc """
  Test function that adds two integers.

  This is the default NIF function generated by Rustler for verification.
  It will be replaced with actual blob storage functions in subsequent tasks.
  """
  @spec add(integer(), integer()) :: integer()
  def add(_a, _b), do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Computes the SHA-256 hash of the given binary data.

  The hash is computed on the raw data as provided - no compression or
  encryption is applied. This ensures consistent content addressing
  regardless of storage format.

  ## Parameters
    - `data` - Binary data to hash

  ## Returns
    - A 32-byte binary containing the SHA-256 hash

  ## Examples

      iex> hash = NeonFS.Core.Blob.Native.compute_hash("hello world")
      iex> byte_size(hash)
      32

  """
  @spec compute_hash(binary()) :: binary()
  def compute_hash(_data), do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Opens a blob store at the given base directory.

  The store manages content-addressed chunk storage on disk using a sharded
  directory hierarchy based on hash prefixes.

  ## Parameters
    - `base_dir` - Path to the base directory for blob storage
    - `prefix_depth` - Number of prefix directory levels (e.g., 2 for 65K directories)

  ## Returns
    - `{:ok, store}` - A reference to the opened store
    - `{:error, reason}` - If the store could not be opened

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> is_reference(store)
      true

  """
  @spec store_open(String.t(), non_neg_integer()) :: {:ok, store()} | {:error, String.t()}
  def store_open(_base_dir, _prefix_depth), do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Writes a chunk to the blob store.

  The chunk is written atomically using a write-then-rename pattern to prevent
  partial chunks on disk. If a chunk with the same hash already exists, this
  operation is idempotent.

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - 32-byte binary hash of the chunk data
    - `data` - Binary data to write
    - `tier` - Storage tier ("hot", "warm", or "cold")

  ## Returns
    - `{:ok, {}}` - On success
    - `{:error, reason}` - If the write fails

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> data = "hello world"
      iex> hash = NeonFS.Core.Blob.Native.compute_hash(data)
      iex> {:ok, _} = NeonFS.Core.Blob.Native.store_write_chunk(store, hash, data, "hot")

  """
  @spec store_write_chunk(store(), hash(), binary(), tier()) :: {:ok, {}} | {:error, String.t()}
  def store_write_chunk(_store, _hash, _data, _tier), do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Reads a chunk from the blob store.

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - 32-byte binary hash of the chunk
    - `tier` - Storage tier ("hot", "warm", or "cold")

  ## Returns
    - `{:ok, data}` - The chunk data as a binary
    - `{:error, reason}` - If the chunk does not exist or read fails

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> data = "hello world"
      iex> hash = NeonFS.Core.Blob.Native.compute_hash(data)
      iex> {:ok, _} = NeonFS.Core.Blob.Native.store_write_chunk(store, hash, data, "hot")
      iex> {:ok, read_data} = NeonFS.Core.Blob.Native.store_read_chunk(store, hash, "hot")
      iex> read_data == data
      true

  """
  @spec store_read_chunk(store(), hash(), tier()) :: {:ok, binary()} | {:error, String.t()}
  def store_read_chunk(_store, _hash, _tier), do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Reads a chunk from the blob store with optional verification.

  When `verify` is true, the function computes the SHA-256 hash of the data
  after reading and compares it to the expected hash. If they don't match,
  an error is returned indicating the chunk is corrupt.

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - 32-byte binary hash of the chunk
    - `tier` - Storage tier ("hot", "warm", or "cold")
    - `verify` - If true, verify the data matches the expected hash

  ## Returns
    - `{:ok, data}` - The chunk data as a binary
    - `{:error, reason}` - If the chunk does not exist, read fails, or verification fails

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> data = "hello world"
      iex> hash = NeonFS.Core.Blob.Native.compute_hash(data)
      iex> {:ok, _} = NeonFS.Core.Blob.Native.store_write_chunk(store, hash, data, "hot")
      iex> {:ok, read_data} = NeonFS.Core.Blob.Native.store_read_chunk_verified(store, hash, "hot", true)
      iex> read_data == data
      true

  """
  @spec store_read_chunk_verified(store(), hash(), tier(), boolean()) ::
          {:ok, binary()} | {:error, String.t()}
  def store_read_chunk_verified(_store, _hash, _tier, _verify),
    do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Deletes a chunk from the blob store.

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - 32-byte binary hash of the chunk
    - `tier` - Storage tier ("hot", "warm", or "cold")

  ## Returns
    - `{:ok, {}}` - On success
    - `{:error, reason}` - If the chunk does not exist or delete fails

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> data = "hello world"
      iex> hash = NeonFS.Core.Blob.Native.compute_hash(data)
      iex> {:ok, _} = NeonFS.Core.Blob.Native.store_write_chunk(store, hash, data, "hot")
      iex> {:ok, _} = NeonFS.Core.Blob.Native.store_delete_chunk(store, hash, "hot")

  """
  @spec store_delete_chunk(store(), hash(), tier()) :: {:ok, {}} | {:error, String.t()}
  def store_delete_chunk(_store, _hash, _tier), do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Checks if a chunk exists in the blob store.

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - 32-byte binary hash of the chunk
    - `tier` - Storage tier ("hot", "warm", or "cold")

  ## Returns
    - `{:ok, true}` - If the chunk exists
    - `{:ok, false}` - If the chunk does not exist
    - `{:error, reason}` - If the check fails

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> hash = NeonFS.Core.Blob.Native.compute_hash("test")
      iex> {:ok, false} = NeonFS.Core.Blob.Native.store_chunk_exists(store, hash, "hot")

  """
  @spec store_chunk_exists(store(), hash(), tier()) :: {:ok, boolean()} | {:error, String.t()}
  def store_chunk_exists(_store, _hash, _tier), do: :erlang.nif_error(:nif_not_loaded)

  @type compression :: String.t()
  @type chunk_info :: {non_neg_integer(), non_neg_integer(), compression()}

  @doc """
  Writes a chunk to the blob store with optional compression.

  The hash is computed on the original (uncompressed) data. If compression is
  enabled, the data is compressed before writing to disk, but the hash still
  refers to the original data for content addressing.

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - 32-byte binary hash of the original (uncompressed) chunk data
    - `data` - Binary data to write
    - `tier` - Storage tier ("hot", "warm", or "cold")
    - `compression` - Compression type: "none" or "zstd"
    - `compression_level` - Compression level (1-19, used for zstd only)

  ## Returns
    - `{:ok, {original_size, stored_size, compression}}` - On success, where:
      - `original_size` - Size of the original uncompressed data
      - `stored_size` - Size of the data as stored on disk (compressed or not)
      - `compression` - The compression used ("none" or "zstd:N")
    - `{:error, reason}` - If the write fails

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> data = String.duplicate("hello world", 1000)
      iex> hash = NeonFS.Core.Blob.Native.compute_hash(data)
      iex> {:ok, {orig, stored, comp}} = NeonFS.Core.Blob.Native.store_write_chunk_compressed(
      ...>   store, hash, data, "hot", "zstd", 3
      ...> )
      iex> stored < orig
      true
      iex> comp
      "zstd:3"

  """
  @spec store_write_chunk_compressed(
          store(),
          hash(),
          binary(),
          tier(),
          compression(),
          integer()
        ) :: {:ok, chunk_info()} | {:error, String.t()}
  def store_write_chunk_compressed(_store, _hash, _data, _tier, _compression, _compression_level),
    do: :erlang.nif_error(:nif_not_loaded)

  @doc """
  Reads a chunk from the blob store with optional verification and decompression.

  This is the most flexible read function, supporting both integrity verification
  and transparent decompression.

  ## Parameters
    - `store` - Reference to the blob store
    - `hash` - 32-byte binary hash of the original (uncompressed) chunk data
    - `tier` - Storage tier ("hot", "warm", or "cold")
    - `verify` - If true, verify the data matches the expected hash after decompression
    - `decompress` - If true, decompress the data after reading

  ## Returns
    - `{:ok, data}` - The chunk data as a binary (decompressed if requested)
    - `{:error, reason}` - If the chunk does not exist, read fails, decompression
      fails, or verification fails

  ## Notes
    - When both `verify` and `decompress` are true, verification happens AFTER
      decompression since the hash is of the original uncompressed data.
    - The Elixir metadata layer tracks which chunks are compressed and passes
      the appropriate `decompress` flag.

  ## Examples

      iex> {:ok, store} = NeonFS.Core.Blob.Native.store_open("/tmp/blobs", 2)
      iex> data = String.duplicate("hello world", 1000)
      iex> hash = NeonFS.Core.Blob.Native.compute_hash(data)
      iex> {:ok, _} = NeonFS.Core.Blob.Native.store_write_chunk_compressed(
      ...>   store, hash, data, "hot", "zstd", 3
      ...> )
      iex> {:ok, read_data} = NeonFS.Core.Blob.Native.store_read_chunk_with_options(
      ...>   store, hash, "hot", true, true
      ...> )
      iex> read_data == data
      true

  """
  @spec store_read_chunk_with_options(store(), hash(), tier(), boolean(), boolean()) ::
          {:ok, binary()} | {:error, String.t()}
  def store_read_chunk_with_options(_store, _hash, _tier, _verify, _decompress),
    do: :erlang.nif_error(:nif_not_loaded)
end
