defmodule NeonFS.Integration.EmergencyBootstrapTest do
  @moduledoc """
  Peer-cluster integration test for `neonfs cluster ca emergency-bootstrap`
  (#460 / #504, sibling to `cluster_ca_rotate_test.exs`).

  Exercises the post-expiry recovery flow on a stopped node:

  1. Bring up a 3-node cluster so each peer has CA material on disk
     (`<tls_dir>/ca.crt`, `<tls_dir>/node.crt`, `<tls_dir>/node.key`)
     and the CA's authoritative copy in the system volume.
  2. Build a backup tarball from the system-volume CA (`ca.crt`,
     `ca.key`, `serial`, `crl.pem`) — that's the off-cluster snapshot
     an operator would have stashed during a normal `cluster ca rotate`.
  3. Stop one peer's BEAM process — emergency-bootstrap refuses to run
     against a live `neonfs-core`, so the test harness simulates the
     "service stopped" precondition the runbook calls out.
  4. Run `neonfs cluster ca emergency-bootstrap --from-backup <tar>`
     as a subprocess against that peer's `tls_dir` and `data_dir`,
     pointing `NEONFS_DIST_PORT_FILE` at a path that does not exist
     so the live-daemon probe stays permissive.
  5. Verify the bootstrap atomically installed the CA material and
     regenerated `node.crt` / `node.key` (DER-fingerprint comparison
     against the pre-bootstrap on-disk cert).

  Does NOT exercise the post-bootstrap `cluster ca rotate` fan-out —
  that path has its own peer-cluster coverage in
  `cluster_ca_rotate_test.exs` (#928). This test focuses on the
  primitive #503 introduced.

  Uses `cluster_mode: :per_test` because emergency-bootstrap rewrites
  one peer's TLS material and restarting that peer cleanly inside a
  shared cluster is more state surgery than the test budget allows.
  """

  use NeonFS.TestSupport.ClusterCase, async: false

  alias NeonFS.TestSupport.PeerCluster
  alias NeonFS.Transport.TLS

  @cli_path Path.expand(
              "../../../neonfs-cli/target/release/neonfs-cli",
              __DIR__
            )

  @moduletag timeout: 300_000
  @moduletag nodes: 3
  @moduletag cluster_mode: :per_test
  @moduletag :integration

  setup %{cluster: cluster} do
    :ok = init_multi_node_cluster(cluster, name: "emergency-bootstrap-test")

    unless File.exists?(@cli_path) do
      flunk(
        "CLI binary not found at #{@cli_path}. Build it with: cd neonfs-cli && cargo build --release"
      )
    end

    :ok
  end

  describe "cluster ca emergency-bootstrap --from-backup" do
    test "atomically installs the backup CA and regenerates node cert on a stopped peer",
         %{cluster: cluster} do
      tarball_path = build_backup_tarball(cluster, :node1)

      pre_node_cert_fingerprint = read_node_cert_fingerprint(cluster, :node1)
      pre_ca_pem = read_local_ca_pem(cluster, :node1)

      tls_dir = peer_tls_dir(cluster, :node1)
      data_dir = peer_data_dir(cluster, :node1)
      assert File.exists?(Path.join(tls_dir, "node.crt"))

      :ok = PeerCluster.stop_node(cluster, :node1)

      env = [
        {"NEONFS_TLS_DIR", tls_dir},
        {"NEONFS_DATA_DIR", data_dir},
        {"NEONFS_DIST_PORT_FILE", missing_dist_port_file()}
      ]

      {output, exit_code} =
        System.cmd(
          @cli_path,
          ["cluster", "ca", "emergency-bootstrap", "--from-backup", tarball_path],
          stderr_to_stdout: true,
          env: env
        )

      assert exit_code == 0,
             "emergency-bootstrap exited #{exit_code}; output:\n#{output}"

      # On-disk CA bytes match the backup we tarred up. install_ca_material
      # writes ca.crt + ca.key + serial + crl.pem atomically per file.
      assert File.exists?(Path.join(tls_dir, "ca.crt"))
      assert File.exists?(Path.join(tls_dir, "ca.key"))
      assert File.exists?(Path.join(tls_dir, "serial"))
      assert File.exists?(Path.join(tls_dir, "crl.pem"))

      assert File.read!(Path.join(tls_dir, "ca.crt")) == pre_ca_pem,
             "installed ca.crt should match the backup we built from the same system volume"

      # node.crt was reissued: a fresh keypair was generated, a CSR
      # was signed against the freshly-installed CA, and the new cert
      # was atomically dropped into place.
      post_node_cert_fingerprint = fingerprint_pem(File.read!(Path.join(tls_dir, "node.crt")))

      refute post_node_cert_fingerprint == pre_node_cert_fingerprint,
             "node.crt should have been regenerated by emergency-bootstrap " <>
               "(fingerprint unchanged: #{pre_node_cert_fingerprint})"

      # Audit trail: emergency-bootstrap appends a JSONL line to
      # `<data_dir>/audit/emergency-bootstrap.log` capturing the source,
      # the cluster identifier, and the before/after CA fingerprints.
      audit_log_path = Path.join([data_dir, "audit", "emergency-bootstrap.log"])
      assert File.exists?(audit_log_path)

      audit_log_lines =
        audit_log_path
        |> File.read!()
        |> String.split("\n", trim: true)

      refute audit_log_lines == []

      audit_entry =
        audit_log_lines
        |> List.last()
        |> :json.decode()

      assert audit_entry["event"] == "cluster_ca_emergency_bootstrap_completed"
      assert is_binary(audit_entry["cluster_id"])
      assert is_binary(audit_entry["new_ca_fingerprint"])
      assert is_binary(audit_entry["timestamp"])
      assert audit_entry["source"] =~ "backup"
    end
  end

  defp build_backup_tarball(cluster, node_name) do
    {:ok, ca_crt} =
      PeerCluster.rpc(cluster, node_name, NeonFS.Core.SystemVolume, :read, ["/tls/ca.crt"])

    {:ok, ca_key} =
      PeerCluster.rpc(cluster, node_name, NeonFS.Core.SystemVolume, :read, ["/tls/ca.key"])

    {:ok, serial} =
      PeerCluster.rpc(cluster, node_name, NeonFS.Core.SystemVolume, :read, ["/tls/serial"])

    {:ok, crl_pem} =
      PeerCluster.rpc(cluster, node_name, NeonFS.Core.SystemVolume, :read, ["/tls/crl.pem"])

    tarball_path =
      Path.join(System.tmp_dir!(), "ca-backup-#{:rand.uniform(1_000_000_000)}.tar.gz")

    members = [
      {~c"ca.crt", ca_crt},
      {~c"ca.key", ca_key},
      {~c"serial", serial},
      {~c"crl.pem", crl_pem}
    ]

    :ok = :erl_tar.create(String.to_charlist(tarball_path), members, [:compressed])

    on_exit(fn -> File.rm(tarball_path) end)

    tarball_path
  end

  defp read_node_cert_fingerprint(cluster, node_name) do
    {:ok, cert} = PeerCluster.rpc(cluster, node_name, TLS, :read_local_cert, [])

    cert
    |> X509.Certificate.to_der()
    |> then(&:crypto.hash(:sha256, &1))
    |> Base.encode16(case: :lower)
  end

  defp read_local_ca_pem(cluster, node_name) do
    tls_dir = peer_tls_dir(cluster, node_name)

    PeerCluster.rpc(cluster, node_name, File, :read!, [Path.join(tls_dir, "ca.crt")])
  end

  defp fingerprint_pem(pem) do
    pem
    |> TLS.decode_cert!()
    |> X509.Certificate.to_der()
    |> then(&:crypto.hash(:sha256, &1))
    |> Base.encode16(case: :lower)
  end

  defp peer_data_dir(cluster, node_name) do
    Path.join(cluster.data_dir, Atom.to_string(node_name))
  end

  defp peer_tls_dir(cluster, node_name) do
    Path.join(peer_data_dir(cluster, node_name), "tls")
  end

  defp missing_dist_port_file do
    Path.join(
      System.tmp_dir!(),
      "neonfs-emergency-bootstrap-test-#{:rand.uniform(1_000_000_000)}"
    )
  end
end
