Application.put_env(:kernel, :epmd_module, NeonFS.Epmd)
{:ok, _} = Node.start(:neonfs_core_test, name_domain: :shortnames)

Mimic.copy(NeonFS.Core.ChunkFetcher)
Mimic.copy(NeonFS.Core.BackgroundWorker)
Mimic.copy(NeonFS.IO.Scheduler)
Mimic.copy(NeonFS.Core.BlobStore)
Mimic.copy(NeonFS.Core.ChunkIndex)
Mimic.copy(NeonFS.Core.Replication)
Mimic.copy(NeonFS.Core.ReplicaRepair)
Mimic.copy(NeonFS.Core.VolumeRegistry)
Mimic.copy(NeonFS.Core.Volume.MetadataReader)
Mimic.copy(NeonFS.Core.RaSupervisor)

ExUnit.start(capture_log: true)
