FROM builder AS deps
RUN mkdir /workdir/neonfs-cli
COPY --from=src . /workdir/neonfs-cli
WORKDIR /workdir/neonfs-cli

FROM deps AS releaser
RUN export PATH="/root/.asdf/shims:$PATH"; cargo build --release

FROM debian:trixie
COPY --from=releaser /workdir/neonfs-cli/target/release/neonfs-cli /bin/neonfs

ENTRYPOINT ["/bin/neonfs"]
