FROM base

LABEL org.opencontainers.image.source="https://harton.dev/project-neon/neonfs" \
      org.opencontainers.image.url="https://harton.dev/project-neon/neonfs" \
      org.opencontainers.image.licenses="Apache-2.0" \
      org.opencontainers.image.title="neonfs-dev" \
      org.opencontainers.image.description="Development image for NeonFS"

RUN useradd dev
RUN mkdir -p /home/dev
RUN mkdir -p /workdir
RUN chown dev:dev /home/dev
RUN chown dev:dev /workdir
USER dev
ENV HOME=/home/dev
COPY resources/dev_zshrc /home/dev/.zshrc

WORKDIR /workdir
COPY .tool-versions /workdir
RUN /usr/local/bin/asdf_install
RUN export PATH="/home/dev/.asdf/shims:$PATH"; mix local.hex --force && mix local.rebar --force
RUN curl -fsSL https://claude.ai/install.sh | bash
