defmodule NeonFS.FUSE.Native do
  @moduledoc """
  Native Rust NIF bindings for FUSE filesystem operations.

  This module provides low-level bindings to the neonfs_fuse Rust crate,
  which handles FUSE filesystem operations via the fuser library.
  """

  use Rustler,
    otp_app: :neonfs_fuse,
    crate: :neonfs_fuse

  @doc """
  Test function that adds two integers.

  This is the default NIF function generated by Rustler for verification.
  It will be replaced with actual FUSE functions in subsequent tasks.
  """
  @spec add(integer(), integer()) :: integer()
  def add(_a, _b), do: :erlang.nif_error(:nif_not_loaded)
end
