defmodule NeonFS.TLSDistConfig do
  @moduledoc """
  Manages `ca_bundle.crt` and `ssl_dist.conf` for TLS distribution.

  On first boot, the daemon wrapper script generates a local CA, daemon cert,
  and CLI cert via openssl. This module handles regeneration of the derived
  config files after cluster init or join, when the cluster CA and
  cluster-signed node cert become available.

  ## File layout

      /var/lib/neonfs/tls/
      ├── local-ca.crt        # Generated by daemon wrapper (openssl)
      ├── local-ca.key        # Generated by daemon wrapper (openssl)
      ├── node-local.crt      # Daemon's local dist cert
      ├── node-local.key      # Daemon's local dist key
      ├── cli.crt             # CLI client cert
      ├── cli.key             # CLI client key
      ├── ca.crt              # Cluster CA cert (after init/join)
      ├── node.crt            # Cluster-signed node cert (after init/join)
      ├── node.key            # Cluster node key (after init/join)
      ├── ca_bundle.crt       # Trust anchors — managed by this module
      └── ssl_dist.conf       # Distribution TLS config — managed by this module

  """

  alias NeonFS.Transport.TLS

  @doc """
  Regenerates `ca_bundle.crt` from available CA certificates.

  The bundle always contains `local-ca.crt`. If the cluster CA cert
  (`ca.crt`) is present, it is appended to the bundle.
  """
  @spec regenerate_ca_bundle(String.t()) :: :ok
  def regenerate_ca_bundle(tls_dir \\ TLS.tls_dir()) do
    bundle_path = Path.join(tls_dir, "ca_bundle.crt")
    local_ca_path = Path.join(tls_dir, "local-ca.crt")
    cluster_ca_path = Path.join(tls_dir, "ca.crt")

    parts =
      [local_ca_path, cluster_ca_path]
      |> Enum.flat_map(fn path ->
        case File.read(path) do
          {:ok, pem} -> [pem]
          {:error, :enoent} -> []
        end
      end)

    if parts == [] do
      :ok
    else
      File.write!(bundle_path, Enum.join(parts))
      File.chmod!(bundle_path, 0o644)
      :ok
    end
  end

  @doc """
  Regenerates `ssl_dist.conf` for Erlang TLS distribution.

  Pre-cluster: uses only `node-local.crt`/`node-local.key`.
  Post-cluster: lists the cluster node cert first in `certs_keys`
  (preferred for inter-node connections), with the local cert as fallback.
  """
  @spec regenerate_config(String.t()) :: :ok
  def regenerate_config(tls_dir \\ TLS.tls_dir()) do
    certs_keys = build_certs_keys(tls_dir)

    if certs_keys == "" do
      :ok
    else
      conf_path = Path.join(tls_dir, "ssl_dist.conf")

      conf = """
      [{server, [
        {certs_keys, [#{certs_keys}]},
        {cacertfile, "#{Path.join(tls_dir, "ca_bundle.crt")}"},
        {verify, verify_peer},
        {fail_if_no_peer_cert, true},
        {versions, ['tlsv1.3']}
      ]},
      {client, [
        {certs_keys, [#{certs_keys}]},
        {cacertfile, "#{Path.join(tls_dir, "ca_bundle.crt")}"},
        {verify, verify_peer},
        {versions, ['tlsv1.3']}
      ]}].
      """

      File.write!(conf_path, conf)
      File.chmod!(conf_path, 0o644)

      :ok
    end
  end

  @doc """
  Regenerates both `ca_bundle.crt` and `ssl_dist.conf`.

  Call after cluster init or join once the cluster CA cert and
  cluster-signed node cert have been written to disk.
  """
  @spec regenerate(String.t()) :: :ok
  def regenerate(tls_dir \\ TLS.tls_dir()) do
    :ok = regenerate_ca_bundle(tls_dir)
    :ok = regenerate_config(tls_dir)
    :ok
  end

  defp build_certs_keys(tls_dir) do
    cluster_cert = Path.join(tls_dir, "node.crt")
    cluster_key = Path.join(tls_dir, "node.key")
    local_cert = Path.join(tls_dir, "node-local.crt")
    local_key = Path.join(tls_dir, "node-local.key")

    entries =
      [
        {cluster_cert, cluster_key},
        {local_cert, local_key}
      ]
      |> Enum.filter(fn {cert, key} -> File.exists?(cert) and File.exists?(key) end)
      |> Enum.map(fn {cert, key} -> cert_key_entry(cert, key) end)

    Enum.join(entries, ", ")
  end

  defp cert_key_entry(certfile, keyfile) do
    "\#{certfile => \"#{certfile}\", keyfile => \"#{keyfile}\"}"
  end
end
