defmodule NeonFS.TLSDistConfig do
  @moduledoc """
  Manages `ca_bundle.crt` and `ssl_dist.conf` for TLS distribution.

  On first boot, the daemon wrapper script generates a local CA, daemon cert,
  and CLI cert via openssl. This module handles regeneration of the derived
  config files after cluster init or join, when the cluster CA and
  cluster-signed node cert become available.

  ## File layout

      /var/lib/neonfs/tls/
      ├── local-ca.crt        # Generated by daemon wrapper (openssl)
      ├── local-ca.key        # Generated by daemon wrapper (openssl)
      ├── node-local.crt      # Daemon's local dist cert
      ├── node-local.key      # Daemon's local dist key
      ├── cli.crt             # CLI client cert
      ├── cli.key             # CLI client key
      ├── ca.crt              # Cluster CA cert (after init/join)
      ├── incoming-ca.crt     # Staged cluster CA (during `cluster ca rotate`)
      ├── node.crt            # Cluster-signed node cert (after init/join)
      ├── node.key            # Cluster node key (after init/join)
      ├── ca_bundle.crt       # Trust anchors — managed by this module
      └── ssl_dist.conf       # Distribution TLS config — managed by this module

  """

  alias NeonFS.Transport.TLS

  @doc """
  Regenerates `ca_bundle.crt` from available CA certificates.

  The bundle always contains `local-ca.crt` first (boot-time daemon CA).
  When a `cluster ca rotate` is in progress, `incoming-ca.crt` is
  appended next so the node trusts certs signed by the staged CA. The
  active cluster CA (`ca.crt`) is appended last.

  Bundle order doesn't affect X.509 verification — any anchor in the
  bundle that signs the chain works — but listing incoming before
  active matches the rotation's "preferred" semantics.
  """
  @spec regenerate_ca_bundle(String.t()) :: :ok
  def regenerate_ca_bundle(tls_dir \\ TLS.tls_dir()) do
    bundle_path = Path.join(tls_dir, "ca_bundle.crt")

    parts =
      tls_dir
      |> bundle_sources()
      |> Enum.flat_map(fn path ->
        case File.read(path) do
          {:ok, pem} -> [pem]
          {:error, :enoent} -> []
        end
      end)

    if parts == [] do
      :ok
    else
      File.write!(bundle_path, Enum.join(parts))
      File.chmod!(bundle_path, 0o644)
      :ok
    end
  end

  @doc """
  Regenerates `ssl_dist.conf` for Erlang TLS distribution.

  Pre-cluster: uses only `node-local.crt`/`node-local.key`.
  Post-cluster: uses only the cluster node cert (`node.crt`/`node.key`).

  We deliberately do NOT keep the local cert as a fallback alongside the
  cluster cert: OTP's TLS 1.3 `certs_keys` selection cannot be relied on to
  pick the cluster cert for a peer connection, and when it picks the local
  (self-signed) cert the peer rejects it with "Unknown CA". Every
  verifier — peer nodes and the local CLI — trusts the cluster CA via
  `ca_bundle.crt` once the node has joined, so presenting the cluster cert
  alone is both sufficient and unambiguous.
  """
  @spec regenerate_config(String.t()) :: :ok
  def regenerate_config(tls_dir \\ TLS.tls_dir()) do
    certs_keys = build_certs_keys(tls_dir)

    if certs_keys == "" do
      :ok
    else
      conf_path = Path.join(tls_dir, "ssl_dist.conf")

      conf = """
      [{server, [
        {certs_keys, [#{certs_keys}]},
        {cacertfile, "#{Path.join(tls_dir, "ca_bundle.crt")}"},
        {verify, verify_peer},
        {fail_if_no_peer_cert, true},
        {versions, ['tlsv1.3']}
      ]},
      {client, [
        {certs_keys, [#{certs_keys}]},
        {cacertfile, "#{Path.join(tls_dir, "ca_bundle.crt")}"},
        {verify, verify_peer},
        {versions, ['tlsv1.3']}
      ]}].
      """

      File.write!(conf_path, conf)
      File.chmod!(conf_path, 0o644)

      :ok
    end
  end

  @doc """
  Regenerates both `ca_bundle.crt` and `ssl_dist.conf`.

  Call after cluster init or join once the cluster CA cert and
  cluster-signed node cert have been written to disk.
  """
  @spec regenerate(String.t()) :: :ok
  def regenerate(tls_dir \\ TLS.tls_dir()) do
    :ok = regenerate_ca_bundle(tls_dir)
    :ok = regenerate_config(tls_dir)
    :ok
  end

  @doc """
  Atomically installs a new node cert + key into the local TLS dir.

  Used by the `cluster ca rotate` orchestrator during the
  rolling reissue: each node's existing cluster cert is replaced with
  one signed by the staged incoming CA. Writes both files via
  temp-file + rename so a crash mid-write leaves the existing
  `node.crt` / `node.key` intact.

  The cert is written 0644, the key 0600 (the daemon must read both;
  only the daemon should be able to read the key).

  Emits `[:neonfs, :tls, :node_cert_installed]` telemetry on success.

  No listener restart is needed for the running daemon to present the
  new pair. What `ssl_dist_sup` caches at listener start is the *option
  list* from `ssl_dist.conf`, and the entries in it are file **paths** —
  the paths here don't change, so the cached options stay correct.
  `inet_tls_dist` resolves them per handshake through the distribution
  PEM cache, whose validator invalidates any cached file whose mtime
  moved; the delay is therefore bounded by `ssl_pem_cache_clean`, 120 s
  by default. Established connections keep the pair they handshook
  with, as they would across a restart.

  Writing the pair is the whole of the work. See
  `restart_distribution/1` for the one change that does need a restart.
  """
  @spec install_node_cert(TLS.pem(), TLS.pem(), String.t()) :: :ok | {:error, term()}
  def install_node_cert(node_cert_pem, node_key_pem, tls_dir \\ TLS.tls_dir()) do
    with :ok <- write_atomic(Path.join(tls_dir, "node.crt"), node_cert_pem, 0o644),
         :ok <- write_atomic(Path.join(tls_dir, "node.key"), node_key_pem, 0o600) do
      :telemetry.execute(
        [:neonfs, :tls, :node_cert_installed],
        %{},
        %{tls_dir: tls_dir}
      )

      :ok
    end
  end

  @doc """
  Stages the rotation's incoming CA on this node and rebuilds the bundle.

  Called by the `cluster ca rotate` orchestrator on every node once the
  incoming CA has been generated. Until this runs the node's trust
  bundle holds the *active* CA alone, so the certificate the rotation
  just issued it — signed by the incoming CA — chains to an anchor
  nobody trusts.

  Writing the anchor is the whole of the work — no listener restart, on
  the same terms as `install_node_cert/3`: the path is what
  `ssl_dist.conf` caches, and the file behind it is re-read once the
  distribution PEM cache invalidates it, within `ssl_pem_cache_clean`
  (120 s by default). Established connections keep running under the
  trust store they handshook with, which is why the rotation holds a
  grace window before `--finalize` drops the old anchor.

  Emits `[:neonfs, :tls, :incoming_ca_installed]` on success.
  """
  @spec install_incoming_ca(TLS.pem(), String.t()) :: :ok | {:error, term()}
  def install_incoming_ca(ca_pem, tls_dir \\ TLS.tls_dir()) do
    with :ok <- write_atomic(Path.join(tls_dir, "incoming-ca.crt"), ca_pem, 0o644),
         :ok <- regenerate_ca_bundle(tls_dir) do
      :telemetry.execute([:neonfs, :tls, :incoming_ca_installed], %{}, %{tls_dir: tls_dir})
      :ok
    end
  end

  @doc """
  Promotes the rotation's incoming CA to this node's active CA.

  Called on every node by `cluster ca rotate --finalize`. Replaces
  `ca.crt` with the promoted anchor, discards the staged
  `incoming-ca.crt`, and rebuilds the bundle — which is what actually
  drops the superseded CA from the node's trust store. Skipping it
  leaves the old anchor trusted for as long as the node lives, so the
  rotation would reissue every certificate without ever retiring what
  it rotated away from.

  Emits `[:neonfs, :tls, :active_ca_promoted]` on success.
  """
  @spec promote_active_ca(TLS.pem(), String.t()) :: :ok | {:error, term()}
  def promote_active_ca(ca_pem, tls_dir \\ TLS.tls_dir()) do
    with :ok <- write_atomic(Path.join(tls_dir, "ca.crt"), ca_pem, 0o644),
         :ok <- remove_incoming_ca(tls_dir),
         :ok <- regenerate_ca_bundle(tls_dir) do
      :telemetry.execute([:neonfs, :tls, :active_ca_promoted], %{}, %{tls_dir: tls_dir})
      :ok
    end
  end

  @doc """
  Discards a staged incoming CA and rebuilds the bundle.

  Called on every node by `cluster ca rotate --abort`. A node that
  keeps the staged anchor after an abort trusts a CA the cluster has
  thrown away.

  Emits `[:neonfs, :tls, :incoming_ca_discarded]` on success.
  """
  @spec discard_incoming_ca(String.t()) :: :ok | {:error, term()}
  def discard_incoming_ca(tls_dir \\ TLS.tls_dir()) do
    with :ok <- remove_incoming_ca(tls_dir),
         :ok <- regenerate_ca_bundle(tls_dir) do
      :telemetry.execute([:neonfs, :tls, :incoming_ca_discarded], %{}, %{tls_dir: tls_dir})
      :ok
    end
  end

  @doc """
  Reports which CA anchors this node currently holds on disk.

  Read half of the rotation's write operations: `install_incoming_ca/2`,
  `promote_active_ca/2` and `discard_incoming_ca/1` all change what this
  returns. The orchestrator calls it on every node to tell a node that
  finished a rotation from one that was unreachable partway through it —
  a distinction nothing else exposes, because a node left holding a
  stale `incoming-ca.crt` keeps working and so says nothing.

  Fingerprints are `TLS.cert_fingerprint/1` over each anchor, or `nil`
  where the file is absent or unreadable as a certificate. An
  unreadable anchor reads as absent deliberately: for the caller's
  purpose — does this node trust what the cluster says it should — a
  corrupt anchor and a missing one have the same answer.
  """
  @spec local_ca_state(String.t()) ::
          {:ok,
           %{active_ca_fingerprint: String.t() | nil, incoming_ca_fingerprint: String.t() | nil}}
  def local_ca_state(tls_dir \\ TLS.tls_dir()) do
    {:ok,
     %{
       active_ca_fingerprint: anchor_fingerprint(Path.join(tls_dir, "ca.crt")),
       incoming_ca_fingerprint: anchor_fingerprint(Path.join(tls_dir, "incoming-ca.crt"))
     }}
  end

  @doc """
  Restarts Erlang's distribution subsystem in-process so a freshly written
  `ssl_dist.conf` takes effect without a full daemon restart.

  Needed only when `ssl_dist.conf` itself changes, which happens once in a
  node's life: `regenerate_config/1` repoints `certs_keys` from
  `node-local.crt` to the cluster-signed `node.crt` at init or join.
  Replacing the *contents* of a file the config already names — a renewed
  node certificate, a rotated CA bundle — needs nothing from this function;
  see `install_node_cert/3`.

  `ssl_dist_sup:start_link/0` consults `-ssl_dist_optfile` exactly once and
  inserts the result into a named ETS table, which `inet_tls_dist` reads per
  handshake. The table is created by the process that calls `start_link/0`,
  i.e. `net_sup`, so terminating `net_sup` destroys it and restarting the
  child re-consults the file. That restart also re-binds the (fixed) dist
  port via `NeonFS.Epmd`. We can't use `:net_kernel.stop/0` — a node booted
  with `-name` rejects it with `{:error, :not_allowed}` — so we bounce the
  supervisor child directly, which is what OTP does internally.

  This drops every peer connection for the duration (nodedown/nodeup); callers
  invoke it only when the node has no cluster peers yet (right after
  `cluster init`, or during `cluster join` before connecting), so the blast
  radius is empty. Local process state, ETS (other than the dist-owned cache),
  and the running Ra logs all survive — this is not a VM restart.

  Emits `[:neonfs, :tls, :distribution_restarted]` on success.
  """
  @spec restart_distribution(keyword()) :: :ok | {:error, term()}
  def restart_distribution(opts \\ []) do
    if tls_distribution?() do
      do_restart_distribution(opts)
    else
      # No TLS distribution to reload (plain inet_tcp, e.g. test/dev nodes and
      # the in-BEAM peer harness). Bouncing :net_sup there would needlessly tear
      # down the node's distribution, so it's a no-op.
      :ok
    end
  end

  defp do_restart_distribution(opts) do
    retries = Keyword.get(opts, :retries, 5)
    backoff_ms = Keyword.get(opts, :backoff_ms, 200)

    # Drops the *data plane's* view of the newly written certificates.
    # `:ssl.clear_pem_cache/0` deliberately leaves the distribution cache
    # alone ("Not supported for distribution at the moment", `ssl_pem_cache`);
    # the `net_sup` bounce below is what discards that one, by taking the
    # process that owns it with it.
    :ssl.clear_pem_cache()

    case dist_sup_id() do
      nil ->
        {:error, :no_distribution_supervisor}

      id ->
        _ = :supervisor.terminate_child(:kernel_sup, id)
        restart_dist_child(id, retries, backoff_ms)
    end
  end

  @doc """
  True only when the node booted with `-proto_dist inet_tls` (the omnibus/daemon
  path). Tests and dev run plain distribution and are never bounced, so callers
  can use this to gate distribution-restart recovery work.
  """
  @spec tls_distribution?() :: boolean()
  def tls_distribution? do
    case :init.get_argument(:proto_dist) do
      {:ok, values} ->
        Enum.any?(values, fn v -> Enum.any?(v, &(to_string(&1) == "inet_tls")) end)

      _ ->
        false
    end
  end

  @doc """
  Blocks until distribution is up again after `restart_distribution/1`, i.e.
  the node has a real name and is alive. Returns `{:error, :timeout}` if it
  doesn't come back within `timeout_ms`.
  """
  @spec await_distribution(non_neg_integer()) :: :ok | {:error, :timeout}
  def await_distribution(timeout_ms \\ 5_000) do
    deadline = System.monotonic_time(:millisecond) + timeout_ms
    do_await_distribution(deadline)
  end

  defp do_await_distribution(deadline) do
    cond do
      Node.alive?() and Node.self() != :nonode@nohost ->
        :ok

      System.monotonic_time(:millisecond) >= deadline ->
        {:error, :timeout}

      true ->
        Process.sleep(50)
        do_await_distribution(deadline)
    end
  end

  defp dist_sup_id do
    :kernel_sup
    |> :supervisor.which_children()
    |> Enum.find_value(fn
      {id, _pid, _type, _mods} when id in [:net_sup, :net_sup_dynamic] -> id
      _ -> nil
    end)
  end

  # The freshly released dist port may not be re-bindable for a few ms, so
  # retry on any restart error rather than failing the whole join/init.
  defp restart_dist_child(_id, retries, _backoff_ms) when retries < 0,
    do: {:error, :restart_exhausted}

  defp restart_dist_child(id, retries, backoff_ms) do
    case :supervisor.restart_child(:kernel_sup, id) do
      {:ok, _pid} ->
        distribution_restarted()

      {:ok, _pid, _info} ->
        distribution_restarted()

      {:error, :running} ->
        distribution_restarted()

      {:error, {:already_started, _pid}} ->
        distribution_restarted()

      {:error, _reason} when retries > 0 ->
        Process.sleep(backoff_ms)
        restart_dist_child(id, retries - 1, backoff_ms)

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp distribution_restarted do
    :telemetry.execute([:neonfs, :tls, :distribution_restarted], %{}, %{})
    :ok
  end

  # Temp-file + rename, so a crash mid-write leaves the existing file intact
  # rather than a half-written certificate the listener will try to load.
  defp write_atomic(path, contents, mode) do
    tmp = path <> ".tmp"

    with :ok <- File.write(tmp, contents),
         :ok <- File.chmod(tmp, mode) do
      File.rename(tmp, path)
    end
  end

  defp anchor_fingerprint(path) do
    with {:ok, pem} <- File.read(path),
         {:ok, cert} <- X509.Certificate.from_pem(pem) do
      TLS.cert_fingerprint(cert)
    else
      _ -> nil
    end
  end

  defp remove_incoming_ca(tls_dir) do
    case File.rm(Path.join(tls_dir, "incoming-ca.crt")) do
      :ok -> :ok
      {:error, :enoent} -> :ok
      {:error, reason} -> {:error, reason}
    end
  end

  defp bundle_sources(tls_dir) do
    [
      Path.join(tls_dir, "local-ca.crt"),
      Path.join(tls_dir, "incoming-ca.crt"),
      Path.join(tls_dir, "ca.crt")
    ]
  end

  # Prefer the cluster cert once it exists (post-join); otherwise fall back to
  # the boot-time local cert (pre-cluster). Exactly one entry is emitted — see
  # `regenerate_config/1` for why we never list both at once.
  defp build_certs_keys(tls_dir) do
    cluster = {Path.join(tls_dir, "node.crt"), Path.join(tls_dir, "node.key")}
    local = {Path.join(tls_dir, "node-local.crt"), Path.join(tls_dir, "node-local.key")}

    cond do
      pair_exists?(cluster) -> cert_key_entry(elem(cluster, 0), elem(cluster, 1))
      pair_exists?(local) -> cert_key_entry(elem(local, 0), elem(local, 1))
      true -> ""
    end
  end

  defp pair_exists?({cert, key}), do: File.exists?(cert) and File.exists?(key)

  defp cert_key_entry(certfile, keyfile) do
    "\#{certfile => \"#{certfile}\", keyfile => \"#{keyfile}\"}"
  end
end
