{{- if and (not .Values.bootstrap.existingSecret) .Values.bootstrap.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "neonfs-csi.bootstrapSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neonfs-csi.commonLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.bootstrap.secretKey }}: {{ .Values.bootstrap.value | quote }}
{{- end }}
