{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "neonfs-csi.controllerServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neonfs-csi.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "neonfs-csi.nodeServiceAccount" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neonfs-csi.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: node
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
